import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAuth } from '../lib/auth';

export default function Home() {
  const { currentUser, signInWithGithub, logOut } = useAuth();

  console.log(currentUser);
  return (
    <div className={styles.container}>
      <Head>
        <title>Fast Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fast Feedback
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {
          currentUser
          ? 
            <button onClick={ (e) => logOut() }>Log Out</button>
          :
            <>
              <button onClick={ (e) => signInWithGithub() }>Sign In With GitHub</button>
              {/* <button onClick={ (e) => signInWithGoogle() }>Sign In With Google</button>
              <br /> */}
            </>
        }

        <p>Welcome {currentUser ? currentUser.displayName : null }</p>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
